### ISSUE TITLE
Logic error in rendering appropriate borders

### ISSUE THREAD

**Issue by hyuangpei** [abyanmajid/dyckvis#1]
For example, let n = 5, and you'd notice starting from the 7th path there will always be one up step that is misplaced to the right by one unit
<img width="224" alt="Screenshot 2023-10-02 123203" src="https://github.com/abyanmajid/dyckvis/assets/145170458/bbe8f7ab-b322-4777-a0dd-3f5986b33509">

**Comment by abyanmajid** [comment]
Resolved.

There was an appending of incorrect classes to the list of classes of the currently selected square.

**Comment by abyanmajid** [comment]
Resolved.

There was an appending of incorrect classes to the list of classes of the currently selected square.
