### ISSUE TITLE
Logic error in rendering appropriate borders

### ISSUE THREAD

**Issue by luoshanyuan** [abyanmajid/dyckvis#2]
For example, let n = 5, and the 7th path and onwards renders the next UP step shifted by one unit to the right.
<img width="224" alt="Screenshot 2023-10-02 123203" src="https://github.com/abyanmajid/dyckvis/assets/145170458/0deef162-d2c1-47d5-af0b-94291c6abcc4">

**Comment by abyanmajid** [comment]
Resolved.

There was an appending of incorrect classes into the class list of current square.
